import LoadCSS from '@/src/utils/LoadCSS';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-pokedex-100">
        {children}
        <LoadCSS />
      </body>
    </html>
  );
}
