import './globals.css';
import { LoadCSS } from '@/src/utils';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <LoadCSS />
      </body>
    </html>
  );
}
